//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acuerdo
    {
        public long idAcuerdo { get; set; }
        public string idUsuario { get; set; }
        public Nullable<long> idAsociacion { get; set; }
        public Nullable<long> idRegional { get; set; }
        public Nullable<long> idAsiento { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> idTipoAcuerdo { get; set; }
        public string numeroGaceta { get; set; }
        public string nota { get; set; }
    
        public virtual Asociacion Asociacion { get; set; }
        public virtual Regional Regional { get; set; }
        public virtual TipoAcuerdo TipoAcuerdo { get; set; }
    }
}
