//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asociacion()
        {
            this.Acuerdo = new HashSet<Acuerdo>();
            this.Miembro = new HashSet<Miembro>();
        }
    
        public long idAsociacion { get; set; }
        public long idRegion { get; set; }
        public int idProvincia { get; set; }
        public int idCanton { get; set; }
        public int idDistrito { get; set; }
        public Nullable<int> idTamanio { get; set; }
        public Nullable<int> idTipo { get; set; }
        public Nullable<int> idEstadoAsoc { get; set; }
        public Nullable<int> cedula_juridica { get; set; }
        public string nombreAsociacion { get; set; }
        public string nombreAsocAnterior { get; set; }
        public string objetivoAsociacion { get; set; }
        public Nullable<System.DateTime> fechaPreConsAsociacon { get; set; }
        public Nullable<System.DateTime> fechaConsAsociacion { get; set; }
        public Nullable<System.DateTime> fechaVencAsociacion { get; set; }
        public Nullable<int> cantidadRenovaciones { get; set; }
        public Nullable<int> cantidadIntegrantes { get; set; }
        public string emailAsociacion { get; set; }
        public string web { get; set; }
        public string numeroTelefono { get; set; }
        public string fax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acuerdo> Acuerdo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miembro> Miembro { get; set; }
        public virtual EstadoAsociacion EstadoAsociacion { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Region Region { get; set; }
        public virtual TipoAsociacion TipoAsociacion { get; set; }
    }
}
