//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_puestojunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dna_puestojunta()
        {
            this.dna_miembrosjunta = new HashSet<dna_miembrosjunta>();
        }
    
        public int id { get; set; }
        public byte habilitado { get; set; }
        public int pos { get; set; }
        public string nombre { get; set; }
        public byte requerido { get; set; }
        public byte mostrar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dna_miembrosjunta> dna_miembrosjunta { get; set; }
    }
}
