//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_bitacora_imprimibles
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string reporte { get; set; }
        public string parametros { get; set; }
        public int usuario_id { get; set; }
        public string descripcion { get; set; }
    }
}
