//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_bitacora
    {
        public int id { get; set; }
        public Nullable<int> asociacion_id { get; set; }
        public int usuario_id { get; set; }
        public string accion { get; set; }
        public byte[] date { get; set; }
        public string valor { get; set; }
    }
}
