//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dna_persona()
        {
            this.dna_miembrosjunta = new HashSet<dna_miembrosjunta>();
            this.dna_resolucionlegalasamblea = new HashSet<dna_resolucionlegalasamblea>();
        }
    
        public Nullable<byte> nacional { get; set; }
        public Nullable<int> paisorigen { get; set; }
        public string cedula { get; set; }
        public string codigo_electoral { get; set; }
        public string sexo { get; set; }
        public string vencimiento { get; set; }
        public string junta_votacion { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public Nullable<System.DateTime> nacimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dna_miembrosjunta> dna_miembrosjunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dna_resolucionlegalasamblea> dna_resolucionlegalasamblea { get; set; }
    }
}
