//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_cambiospresi
    {
        public int id { get; set; }
        public Nullable<int> junta_id { get; set; }
        public Nullable<int> puesto_id { get; set; }
        public string persona_id { get; set; }
        public Nullable<int> acuerdo_id { get; set; }
        public Nullable<int> asociacion_id { get; set; }
        public byte[] stamp { get; set; }
        public Nullable<System.DateTime> fecha_cambio_presi { get; set; }
    }
}
