//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_resolucionlegalasamblea
    {
        public int id { get; set; }
        public int asociacion_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string oficio { get; set; }
        public string titulo { get; set; }
        public string presidente_id { get; set; }
        public byte cumple_parametros { get; set; }
        public byte req_limite { get; set; }
        public byte req_domicilio { get; set; }
        public byte req_objetivos { get; set; }
        public byte req_requisitosafiliados { get; set; }
        public byte req_ausencias { get; set; }
        public byte req_miembro { get; set; }
        public byte req_vocales { get; set; }
        public byte req_atribuciones { get; set; }
        public byte req_suplenciamiembros { get; set; }
        public byte req_reeleccion { get; set; }
        public string req_otro { get; set; }
        public int responsable_id { get; set; }
        public string referencia { get; set; }
    
        public virtual dna_persona dna_persona { get; set; }
    }
}
