//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_miembrosjunta
    {
        public int id { get; set; }
        public int junta_id { get; set; }
        public int puesto_id { get; set; }
        public string persona_id { get; set; }
        public byte nuevo { get; set; }
        public string salvedad { get; set; }
        public Nullable<byte> activo_import { get; set; }
    
        public virtual dna_puestojunta dna_puestojunta { get; set; }
        public virtual dna_persona dna_persona { get; set; }
    }
}
