//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_acuerdo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dna_acuerdo()
        {
            this.dna_juntadirectiva = new HashSet<dna_juntadirectiva>();
        }
    
        public int id { get; set; }
        public int asociacion_id { get; set; }
        public int ano { get; set; }
        public int numero { get; set; }
        public Nullable<int> tomo { get; set; }
        public Nullable<short> folio { get; set; }
        public Nullable<int> asiento { get; set; }
        public System.DateTime fecha { get; set; }
        public byte[] fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<System.DateTime> fecha_asamblea { get; set; }
        public Nullable<System.DateTime> fecha_publicacion_gaceta { get; set; }
        public string numero_gaceta { get; set; }
        public string tipo { get; set; }
        public string detalle { get; set; }
        public string nota1 { get; set; }
        public string nota2 { get; set; }
        public int responsable_id { get; set; }
        public Nullable<int> acuerdo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dna_juntadirectiva> dna_juntadirectiva { get; set; }
    }
}
