//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_asientos
    {
        public int id { get; set; }
        public Nullable<int> tomo { get; set; }
        public Nullable<int> folio { get; set; }
        public Nullable<int> asiento { get; set; }
        public Nullable<int> periodo { get; set; }
        public Nullable<int> codigo_acuerdo { get; set; }
        public byte[] fecha_creacion { get; set; }
        public Nullable<int> acuerdo_id { get; set; }
        public Nullable<byte> importado { get; set; }
    }
}
