//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_inscripcion
    {
        public int id { get; set; }
        public int asociacion_id { get; set; }
        public string cedula { get; set; }
        public int consecutivo { get; set; }
        public System.DateTime creacion { get; set; }
        public System.DateTime inscripcion { get; set; }
        public System.DateTime publicacion { get; set; }
        public System.DateTime vencimiento { get; set; }
        public int num_diaro { get; set; }
        public int numero { get; set; }
        public Nullable<int> tomo { get; set; }
        public Nullable<int> folio { get; set; }
        public Nullable<int> asiento { get; set; }
    }
}
