//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_provincias
    {
        public int OGR_FID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public string nprovincia { get; set; }
        public Nullable<int> num_canto { get; set; }
        public int cod_prov { get; set; }
        public Nullable<int> pob_1950_h { get; set; }
        public Nullable<int> pob_1950_m { get; set; }
        public Nullable<int> pob_1963_h { get; set; }
        public Nullable<int> pob_1963_m { get; set; }
        public Nullable<int> pob_1973_h { get; set; }
        public Nullable<int> pob_1973_m { get; set; }
        public Nullable<int> pob_1984_h { get; set; }
        public Nullable<int> pob_1984_m { get; set; }
    }
}
