//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_cantones
    {
        public int OGR_FID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public string ncanton { get; set; }
        public string nprovincia { get; set; }
        public int prov { get; set; }
        public int canto { get; set; }
    }
}
