//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_impresion
    {
        public int id { get; set; }
        public Nullable<int> asociacion_id { get; set; }
        public int consecutivo { get; set; }
        public System.DateTime fecha { get; set; }
        public int ano { get; set; }
        public byte[] fecha_creacion { get; set; }
        public Nullable<int> num_diaro { get; set; }
        public string detalle { get; set; }
        public int responsable_id { get; set; }
        public string tipo { get; set; }
        public Nullable<int> tipo_anterior { get; set; }
        public string articulos { get; set; }
    
        public virtual dna_responsable dna_responsable { get; set; }
    }
}
