//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_distritos
    {
        public int OGR_FID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public string ndistrito { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> perimetro { get; set; }
        public Nullable<int> prov { get; set; }
        public string provincia { get; set; }
        public string ncanton { get; set; }
        public Nullable<int> coddist { get; set; }
        public Nullable<int> distrito { get; set; }
        public Nullable<int> canton { get; set; }
        public Nullable<int> area_km2 { get; set; }
        public Nullable<int> pob_1997_m { get; set; }
        public Nullable<int> pob_1997_h { get; set; }
        public Nullable<int> pob_2000_h { get; set; }
        public Nullable<int> pob_2000_m { get; set; }
        public Nullable<int> money { get; set; }
        public Nullable<int> bultos { get; set; }
    }
}
