//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_bitacora_imprimibles
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string reporte { get; set; }
        public string parametros { get; set; }
        public int usuario_id { get; set; }
        public string descripcion { get; set; }
    }
}
