//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_v_bitacora
    {
        public Nullable<int> id { get; set; }
        public string accion { get; set; }
        public string accion_h { get; set; }
        public byte[] fecha { get; set; }
        public string fecha_h { get; set; }
        public Nullable<int> asociacion { get; set; }
        public string asociacion_h { get; set; }
        public Nullable<int> tipo { get; set; }
        public string tipo_h { get; set; }
        public Nullable<int> usuario { get; set; }
        public string usuario_h { get; set; }
        public string bitacora { get; set; }
        public string consecutivo { get; set; }
    }
}
