//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_periodo
    {
        public int id { get; set; }
        public int asociacion_id { get; set; }
        public int numero { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime vencimiento { get; set; }
        public System.DateTime asamblea { get; set; }
        public int ano { get; set; }
        public int region_id { get; set; }
        public int provincia_id { get; set; }
        public int canton_id { get; set; }
        public int distrito_id { get; set; }
        public string domicilio { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public string notas { get; set; }
    }
}
