//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dna_regional
    {
        public int id { get; set; }
        public byte habilitado { get; set; }
        public string titulo { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public int region_id { get; set; }
    
        public virtual dna_region dna_region { get; set; }
    }
}
