//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_proyecto
    {
        public int id { get; set; }
        public int id_asociacion { get; set; }
        public string estado { get; set; }
        public int id_tipo { get; set; }
        public int id_subtipo { get; set; }
        public int codigo { get; set; }
        public string codigo_largo { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public int monto_solicitado { get; set; }
        public Nullable<System.DateTime> tramite_fecha { get; set; }
        public string tramite_observaciones { get; set; }
        public string expediente { get; set; }
        public Nullable<System.DateTime> completado_fecha { get; set; }
        public string completado_observaciones { get; set; }
        public Nullable<int> id_aprobacion { get; set; }
    }
}
