//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_proy_aprobacion
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string sesion { get; set; }
        public string acuerdo { get; set; }
        public string boleta { get; set; }
        public int id_partida { get; set; }
        public int monto { get; set; }
        public string observaciones { get; set; }
    }
}
