//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_liquidacion
    {
        public int id { get; set; }
        public int id_deposito { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_liquidacion { get; set; }
        public string gasto { get; set; }
        public Nullable<int> utilizado { get; set; }
        public Nullable<int> reembolsado { get; set; }
        public Nullable<int> id_institucion { get; set; }
        public byte anombremh { get; set; }
        public string comprobante { get; set; }
        public string observaciones { get; set; }
        public Nullable<byte> proy_formulariocompleto { get; set; }
        public Nullable<byte> proy_guia { get; set; }
        public Nullable<byte> dist_facturas { get; set; }
        public Nullable<byte> dist_presentoinforme { get; set; }
        public Nullable<byte> dist_plantrabajo { get; set; }
        public Nullable<byte> dist_personeriaaldia { get; set; }
        public Nullable<byte> dist_cedulaaldia { get; set; }
    }
}
