//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_dist_asignacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dnf_dist_asignacion()
        {
            this.dnf_dist_exclusion = new HashSet<dnf_dist_exclusion>();
            this.dnf_dist_inclusion = new HashSet<dnf_dist_inclusion>();
        }
    
        public int id { get; set; }
        public int id_distribucion { get; set; }
        public int id_asociacion { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public byte activa { get; set; }
        public int monto { get; set; }
    
        public virtual dnf_distribucion dnf_distribucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dnf_dist_exclusion> dnf_dist_exclusion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dnf_dist_inclusion> dnf_dist_inclusion { get; set; }
    }
}
