//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_cuentas
    {
        public int id { get; set; }
        public int id_asociacion { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public byte es_cemento { get; set; }
        public string centro_gestor_1 { get; set; }
        public string centro_gestor_2 { get; set; }
        public string posicion_presupuestaria_1 { get; set; }
        public string posicion_presupuestaria_2 { get; set; }
        public string posicion_presupuestaria_3 { get; set; }
        public string proyectos { get; set; }
        public string isr_cemento { get; set; }
        public string oficio { get; set; }
        public byte revisionSigaf { get; set; }
        public byte registroSigaf { get; set; }
        public byte datoscuenta { get; set; }
    }
}
