//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_tipoproyecto
    {
        public int id { get; set; }
        public byte habilitado { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    }
}
