//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_proy_aprobacion
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string sesion { get; set; }
        public string acuerdo { get; set; }
        public string boleta { get; set; }
        public int id_partida { get; set; }
        public int monto { get; set; }
        public string observaciones { get; set; }
    
        public virtual dnf_partida dnf_partida { get; set; }
    }
}
