//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_dist_inclusion
    {
        public int id { get; set; }
        public int id_distasignacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string razon { get; set; }
        public byte asociacionactiva { get; set; }
        public byte cuentaverificada { get; set; }
        public byte aldiaproyectos { get; set; }
        public byte aldiaisr { get; set; }
    
        public virtual dnf_dist_asignacion dnf_dist_asignacion { get; set; }
    }
}
