//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_dist_aprobacion
    {
        public int id { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_aprobacion { get; set; }
        public System.DateTime fecha_exclusion { get; set; }
        public string resolucion { get; set; }
        public string acuerdo { get; set; }
        public string observaciones { get; set; }
    }
}
