//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_dist_asignacion
    {
        public int id { get; set; }
        public int id_distribucion { get; set; }
        public int id_asociacion { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public byte activa { get; set; }
        public int monto { get; set; }
    }
}
