//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_dist_aprobacion
    {
        public int id { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_aprobacion { get; set; }
        public System.DateTime fecha_exclusion { get; set; }
        public string resolucion { get; set; }
        public string acuerdo { get; set; }
        public string observaciones { get; set; }
    }
}
