//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_distribucion
    {
        public int id { get; set; }
        public byte habilitado { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_corte { get; set; }
        public string resolucion { get; set; }
        public string acuerdo { get; set; }
        public System.DateTime fecha_limite { get; set; }
        public System.DateTime fecha_impresion { get; set; }
        public string tipo { get; set; }
        public int monto { get; set; }
        public int monto_subejecutado { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_aprobacion { get; set; }
        public Nullable<System.DateTime> deposito_fecha { get; set; }
        public string deposito_observaciones { get; set; }
        public Nullable<int> monto_unitario { get; set; }
    }
}
