//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_distribucion
    {
        public int id { get; set; }
        public byte habilitado { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_corte { get; set; }
        public string resolucion { get; set; }
        public string acuerdo { get; set; }
        public System.DateTime fecha_limite { get; set; }
        public System.DateTime fecha_impresion { get; set; }
        public string tipo { get; set; }
        public int monto { get; set; }
        public int monto_subejecutado { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_aprobacion { get; set; }
        public Nullable<System.DateTime> deposito_fecha { get; set; }
        public string deposito_observaciones { get; set; }
        public Nullable<int> monto_unitario { get; set; }
    }
}
