//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_deposito
    {
        public int id { get; set; }
        public Nullable<int> id_distasignacion { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public string observaciones { get; set; }
        public byte proyecto { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_deposito { get; set; }
        public System.DateTime fecha_limite { get; set; }
        public string planilla { get; set; }
    }
}
