//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnf_liquidacion
    {
        public int id { get; set; }
        public int id_deposito { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_liquidacion { get; set; }
        public string gasto { get; set; }
        public Nullable<int> utilizado { get; set; }
        public Nullable<int> reembolsado { get; set; }
        public Nullable<int> id_institucion { get; set; }
        public byte anombremh { get; set; }
        public string comprobante { get; set; }
        public string observaciones { get; set; }
        public Nullable<byte> proy_formulariocompleto { get; set; }
        public Nullable<byte> proy_guia { get; set; }
        public Nullable<byte> dist_facturas { get; set; }
        public Nullable<byte> dist_presentoinforme { get; set; }
        public Nullable<byte> dist_plantrabajo { get; set; }
        public Nullable<byte> dist_personeriaaldia { get; set; }
        public Nullable<byte> dist_cedulaaldia { get; set; }
    }
}
