//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembro
    {
        public long idMiembro { get; set; }
        public Nullable<long> idAsociacion { get; set; }
        public Nullable<long> idPersona { get; set; }
        public Nullable<long> idPuesto { get; set; }
        public Nullable<System.DateTime> fechaIngresoMiembro { get; set; }
        public Nullable<System.DateTime> fechaSalidaMiembro { get; set; }
        public Nullable<long> idJuntaDirectiva { get; set; }
        public Nullable<long> idJuntaDirectivaAnterior { get; set; }
        public Nullable<short> idEstadoMiembro { get; set; }
    
        public virtual Asociacion Asociacion { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
