//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembro
    {
        public long idMiembro { get; set; }
        public Nullable<long> idAsociacion { get; set; }
        public Nullable<long> idPersona { get; set; }
        public Nullable<long> idPuesto { get; set; }
        public Nullable<System.DateTime> fechaIngresoMiembro { get; set; }
        public Nullable<System.DateTime> fechaSalidaMiembro { get; set; }
        public Nullable<long> idJuntaDirectiva { get; set; }
        public Nullable<long> idJuntaDirectivaAnterior { get; set; }
        public Nullable<short> idEstadoMiembro { get; set; }
    
        public virtual Asociacion Asociacion { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
