//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DINADECO_BDEntities : DbContext
    {
        public DINADECO_BDEntities()
            : base("name=DINADECO_BDEntities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acuerdo> Acuerdo { get; set; }
        public virtual DbSet<Asociacion> Asociacion { get; set; }
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<dna_bitacora> dna_bitacora { get; set; }
        public virtual DbSet<dna_bitacora_imprimibles> dna_bitacora_imprimibles { get; set; }
        public virtual DbSet<dnf_deposito> dnf_deposito { get; set; }
        public virtual DbSet<dnf_dist_aprobacion> dnf_dist_aprobacion { get; set; }
        public virtual DbSet<dnf_dist_asignacion> dnf_dist_asignacion { get; set; }
        public virtual DbSet<dnf_dist_exclusion> dnf_dist_exclusion { get; set; }
        public virtual DbSet<dnf_dist_inclusion> dnf_dist_inclusion { get; set; }
        public virtual DbSet<dnf_distribucion> dnf_distribucion { get; set; }
        public virtual DbSet<dnf_institucionesfinancieras> dnf_institucionesfinancieras { get; set; }
        public virtual DbSet<dnf_liquidacion> dnf_liquidacion { get; set; }
        public virtual DbSet<dnf_proy_aprobacion> dnf_proy_aprobacion { get; set; }
        public virtual DbSet<dnf_proy_cambioestado> dnf_proy_cambioestado { get; set; }
        public virtual DbSet<dnf_proyecto> dnf_proyecto { get; set; }
        public virtual DbSet<dnf_subtipoproyecto> dnf_subtipoproyecto { get; set; }
        public virtual DbSet<dnf_tipoproyecto> dnf_tipoproyecto { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<EstadoAsociacion> EstadoAsociacion { get; set; }
        public virtual DbSet<Miembro> Miembro { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Regional> Regional { get; set; }
        public virtual DbSet<TipoAcuerdo> TipoAcuerdo { get; set; }
        public virtual DbSet<TipoAsociacion> TipoAsociacion { get; set; }
    }
}
