//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dinadeco_PruebaEntities : DbContext
    {
        public Dinadeco_PruebaEntities()
            : base("name=Dinadeco_PruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dna_acuerdo> dna_acuerdo { get; set; }
        public virtual DbSet<dna_asientos> dna_asientos { get; set; }
        public virtual DbSet<dna_asociacion> dna_asociacion { get; set; }
        public virtual DbSet<dna_asociacion_historic> dna_asociacion_historic { get; set; }
        public virtual DbSet<dna_bitacora> dna_bitacora { get; set; }
        public virtual DbSet<dna_bitacora_imprimibles> dna_bitacora_imprimibles { get; set; }
        public virtual DbSet<dna_cambiospresi> dna_cambiospresi { get; set; }
        public virtual DbSet<dna_cantones> dna_cantones { get; set; }
        public virtual DbSet<dna_impresion> dna_impresion { get; set; }
        public virtual DbSet<dna_inscripcion> dna_inscripcion { get; set; }
        public virtual DbSet<dna_juntadirectiva> dna_juntadirectiva { get; set; }
        public virtual DbSet<dna_miembrosjunta> dna_miembrosjunta { get; set; }
        public virtual DbSet<dna_pais> dna_pais { get; set; }
        public virtual DbSet<dna_periodo> dna_periodo { get; set; }
        public virtual DbSet<dna_persona> dna_persona { get; set; }
        public virtual DbSet<dna_personas_junta_importacion> dna_personas_junta_importacion { get; set; }
        public virtual DbSet<dna_puestojunta> dna_puestojunta { get; set; }
        public virtual DbSet<dna_region> dna_region { get; set; }
        public virtual DbSet<dna_regional> dna_regional { get; set; }
        public virtual DbSet<dna_resolucionlegal> dna_resolucionlegal { get; set; }
        public virtual DbSet<dna_resolucionlegalasamblea> dna_resolucionlegalasamblea { get; set; }
        public virtual DbSet<dna_responsable> dna_responsable { get; set; }
        public virtual DbSet<dna_tipo> dna_tipo { get; set; }
        public virtual DbSet<dnf_cuentas> dnf_cuentas { get; set; }
        public virtual DbSet<dnf_deposito> dnf_deposito { get; set; }
        public virtual DbSet<dnf_dist_aprobacion> dnf_dist_aprobacion { get; set; }
        public virtual DbSet<dnf_dist_asignacion> dnf_dist_asignacion { get; set; }
        public virtual DbSet<dnf_dist_exclusion> dnf_dist_exclusion { get; set; }
        public virtual DbSet<dnf_dist_inclusion> dnf_dist_inclusion { get; set; }
        public virtual DbSet<dnf_distribucion> dnf_distribucion { get; set; }
        public virtual DbSet<dnf_institucionesfinancieras> dnf_institucionesfinancieras { get; set; }
        public virtual DbSet<dnf_liquidacion> dnf_liquidacion { get; set; }
        public virtual DbSet<dnf_partida> dnf_partida { get; set; }
        public virtual DbSet<dnf_proy_aprobacion> dnf_proy_aprobacion { get; set; }
        public virtual DbSet<dnf_proy_cambioestado> dnf_proy_cambioestado { get; set; }
        public virtual DbSet<dnf_proyecto> dnf_proyecto { get; set; }
        public virtual DbSet<dnf_subtipoproyecto> dnf_subtipoproyecto { get; set; }
        public virtual DbSet<dnf_tipoproyecto> dnf_tipoproyecto { get; set; }
        public virtual DbSet<padron> padrons { get; set; }
        public virtual DbSet<dna_acuerdos_importacion> dna_acuerdos_importacion { get; set; }
        public virtual DbSet<dna_asociacion_importacion> dna_asociacion_importacion { get; set; }
        public virtual DbSet<dna_distritos> dna_distritos { get; set; }
        public virtual DbSet<dna_provincias> dna_provincias { get; set; }
        public virtual DbSet<dna_v_bitacora> dna_v_bitacora { get; set; }
    }
}
