//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class padron
    {
        public string cedula { get; set; }
        public byte sexo { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public Nullable<System.DateTime> nacimiento { get; set; }
        public byte nacional { get; set; }
        public Nullable<int> paisorigen { get; set; }
        public Nullable<System.DateTime> vencimiento { get; set; }
    }
}
