//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_Dinadeco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Regional()
        {
            this.Acuerdo = new HashSet<Acuerdo>();
        }
    
        public long idRegional { get; set; }
        public string nombreRegional { get; set; }
        public string direccionRegional { get; set; }
        public int idProvincia { get; set; }
        public int idCanton { get; set; }
        public int idDistrito { get; set; }
        public string correoRegional { get; set; }
        public Nullable<int> telefonoRegional { get; set; }
        public short idEstadoRegional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acuerdo> Acuerdo { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
